### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by seanoshea** [seanoshea/FuzzyMatchingSwift#1]
Convert library to Swift 3.

**Comment by seanoshea** [comment]
https://www.reddit.com/r/swift/comments/51b0ho/whats_everyone_working_on_this_week_952016/d7bs5jg

**Comment by jozemite** [comment]
More specifically, changing the prefix in the function "sortedByFuzzyMatchPattern" from "sorted" to "sort." It seems that the function only sorts/rearranges the values in the array (correct me if I'm wrong). Like Apple states in the Swift API Design Guidelines, sort is for when a current existing array is mutated, and sorted is for when a new array is returned and assigned to another variable.

**Comment by seanoshea** [comment]
`sortedByFuzzyMatchPattern` currently returns a new array (https://github.com/seanoshea/FuzzyMatchingSwift/blob/develop/FuzzyMatchingSwift/Classes/FuzzyMatching.swift#L50) and doesn't mutate `self`. The new array is returned at https://github.com/seanoshea/FuzzyMatchingSwift/blob/develop/FuzzyMatchingSwift/Classes/FuzzyMatching.swift#L74. By https://swift.org/documentation/api-design-guidelines/#naming, I believe that's the expected behavior?

It is a little odd though, if you look at `Array.sort` code, it returns a new array:
```
extension MutableCollectionType {
    /// Returns an `Array` containing the sorted elements of `source`
    /// according to `isOrderedBefore`.
    ///
    /// The sorting algorithm is not stable (can change the relative order of
    /// elements for which `isOrderedBefore` does not establish an order).
    ///
    /// - Requires: `isOrderedBefore` is a
    ///   [strict weak ordering](http://en.wikipedia.org/wiki/Strict_weak_order#Strict_weak_orderings)
    ///   over the elements in `self`.
    @warn_unused_result(mutable_variant="sortInPlace")
    public func sort(@noescape isOrderedBefore: (Self.Generator.Element, Self.Generator.Element) -> Bool) -> [Self.Generator.Element]
}
```
and tells the reader to use `sortInPlace` if they want the mutating version of sort.
In code terms:
```
    let numbers = [0, 1, 3, 2]
    numbers.sort {
      return $0 < $1
    }
```
`numbers` at the end of this hasn't been mutated. Conversely, if you take:
```
    var numbers = [0, 1, 3, 2]
    numbers.sortInPlace({ (one, two) -> Bool in
      return one < two
    })
```
`numbers` at the end of this has been mutated (note that it had to be declared as a `var`).

So, if I wanted to alter the signature of the original function to be `sortByFuzzyMatchPattern`, I'd need to declare it as a `mutating` public func and not return any Array.

I guess I could offer two alternatives:
 - sortedByFuzzyMatchPattern which returns an array and doesn't mutate the underlying Array.
 - sortInPlaceByFuzzyMatchingPattern which doesn't return an array and mutates the underlying Array?

I think that'd work, but curious to hear your thoughts @jozemite
